apiVersion: v1
kind: Service
metadata:
  name: usdf-butler-misc16-svc
  namespace: misc16-prod
  annotations:
    metallb.universe.tf/address-pool: sdf-services
    #metallb.universe.tf/loadBalancerIPs: 172.24.5.61
spec:
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/cluster: usdf-butler-misc16
    role: primary
  sessionAffinity: None
  type: LoadBalancer
