---
apiVersion: v1
kind: Service
metadata:
  name: usdf-butler-misc16-pooler-transaction-rw  
  namespace: misc16-prod
  annotations:
    metallb.universe.tf/address-pool: sdf-services
    #metallb.universe.tf/loadBalancerIPs: 172.24.5.71
spec:
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/poolerName: usdf-butler-misc16-pooler-transaction-rw
  sessionAffinity: None
---
apiVersion: v1
kind: Service
metadata:
  name: usdf-butler-misc16-pooler-session-rw
  namespace: misc16-prod
  annotations:
    metallb.universe.tf/address-pool: sdf-services
    #metallb.universe.tf/loadBalancerIPs: 172.24.5.70
spec:
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/poolerName: usdf-butler-misc16-pooler-session-rw
  sessionAffinity: None
  