
resources:
- ns.yaml
# cnpg
- cnpg-butler-misc16-database.yaml
- cnpg-butler-misc16-pooler.yaml
#- cnpg-db-svc.yaml
- cnpg-butler-misc16-pooler-service.yaml
- backup.yaml

secretGenerator:
- name: usdf-butler-misc16-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password

- name: s3-creds
  options:
    disableNameSuffixHash: true
  files:
  - ACCESS_KEY_ID=etc/.secrets/client-id
  - ACCESS_SECRET_KEY=etc/.secrets/client-secret

namespace: misc16-prod
# commonLabels:
#   env: misc16-prod
#   app: butler-misc16
#   namespace: misc16-prod
