apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: usdf-butler-embargo16-backup
  namespace: embargo16-prod
spec:
  immediate: true
  schedule: "0 0 0 * * *"
  backupOwnerReference: self
  cluster:
    name: usdf-butler-embargo16

