
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: usdf-butler-restore
spec:
  instances: 1
  primaryUpdateStrategy: unsupervised

  bootstrap:
    recovery:
      source: usdf-butler2
      recoveryTarget:
        backupID: 20230208T000000

  externalClusters:
  - name: usdf-butler2
    barmanObjectStore:
      destinationPath: s3://rubin-usdf-butler
      endpointURL: https://s3dfrgw.slac.stanford.edu
      s3Credentials:
        accessKeyId:
          name: s3-creds
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: s3-creds
          key: ACCESS_SECRET_KEY
      wal:
        maxParallel: 8

  imageName:  us-central1-docker.pkg.dev/prompt-proto/prompt/cnpg-postgresql:14
  imagePullSecrets:
    - name: regcred
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true' 

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  postgresql:
    parameters:
      shared_buffers: 2GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
      work_mem: 160MB
      log_disconnections: on
      log_duration: on
      log_statement: all
      log_min_duration_statement: 250ms


  resources:
    requests:
      memory: 8Gi
      cpu: 4
    limits:
      memory: 16Gi
      cpu: 16

  storage:
    storageClass: wekafs--sdf-k8s01
    size: 1500Gi


