
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: usdf-butler
  namespace: dev
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised

  backup:
    barmanObjectStore:
      destinationPath: s3://rubin-usdf-butler-dev
      endpointURL: https://s3dfrgw.slac.stanford.edu
      s3Credentials:
        accessKeyId:
          key: ACCESS_KEY_ID
          name: s3-creds-dev
        secretAccessKey:
          key: ACCESS_SECRET_KEY
          name: s3-creds-dev
    retentionPolicy: 15d
  
  imageName:  ghcr.io/lsst-sqre/cnpg-postgres-images:14.5
  inheritedMetadata:
    annotations:
      prometheus.io/scrape: 'true' 

  monitoring:
    enablePodMonitor: true

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  postgresql:
    parameters:
        archive_mode: "on"
        archive_timeout: 5min
        dynamic_shared_memory_type: posix
        log_destination: csvlog
        log_directory: /controller/log
        log_disconnections: "on"
        log_duration: "on"
        log_filename: postgres
        log_min_duration_statement: 250ms
        log_rotation_age: "0"
        log_rotation_size: "0"
        log_statement: all
        log_temp_files: "1"
        log_truncate_on_rotation: "false"
        logging_collector: "on"
        maintenance_work_mem: 2GB
        max_connections: "1000"
        max_parallel_workers: "32"
        max_replication_slots: "32"
        max_wal_size: 16GB
        max_worker_processes: "32"
        min_wal_size: 4GB
        pg_stat_statements.max: "10000"
        pg_stat_statements.track: all
        random_page_cost: "1.1"
        shared_buffers: 16GB
        shared_memory_type: mmap
        shared_preload_libraries: ""
        wal_keep_size: 512MB
        wal_receiver_timeout: 5s
        wal_sender_timeout: 5s
        work_mem: 160MB
        max_slot_wal_keep_size: "100GB"
       
  resources:
    requests:
      memory: 64Gi
      cpu: 8
    limits:
      memory: 128Gi
      cpu: 16 

  storage:
    storageClass: wekafs--sdf-k8s01
    size: 20000Gi
