
resources:
- ns.yaml
# cnpg
- cnpg-butler-database.yaml
- cnpg-butler-pooler.yaml

### hmm... the endpoint doens't exist here for kustomize to do anythign abot it; add into Makefile?
#patchesStrategicMerge:
#- endpoints-patch.yaml

secretGenerator:
- name: usdf-butler-butler-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password

#nameSuffix: -dev
namespace: dev
commonLabels:
  env: dev
  app: butler
  namespace: dev

#configMapGenerator:
#- name: telegraf-postgres
#  files:
#  - telegraf.conf
#  - postgresql_custom_data.conf 

