resources:
- ns.yaml
# cnpg
- cnpg-butler-main-database.yaml
- cnpg-butler-main-pooler.yaml

secretGenerator:
- name: usdf-butler-main-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password

namespace: main-dev
commonLabels:
  env: main-dev
  app: butler-main
  namespace: main-dev
