apiVersion: v1
kind: Service
metadata:
  name: usdf-butler-embargo16-svc
  namespace: embargo16-prod
  annotations:
    metallb.universe.tf/address-pool: sdf-services
spec:
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/cluster: usdf-butler-embargo16
    role: primary
  sessionAffinity: None
  type: LoadBalancer

