
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: usdf-butler
spec:
  instances: 2
  primaryUpdateStrategy: unsupervised

  bootstrap:
    initdb:
      database: lsstdb1
      owner: rubin
      secret:
        name: usdf-butler-butler-creds
  
  imageName:  ghcr.io/cloudnative-pg/postgresql:14.4-7

  nodeMaintenanceWindow:
    inProgress: false
    reusePVC: true

  postgresql:
    parameters:
      shared_buffers: 16GB
      pg_stat_statements.max: "10000"
      pg_stat_statements.track: all
    ldap:
      scheme: ldaps
      server: 'ldap-unix.slac.stanford.edu'
      # tls: true
      port: 636
      bindAsAuth:
        prefix: 'uid='
        suffix: ',ou=Accounts,dc=slac,dc=stanford,dc=edu'


  resources:
    requests:
      memory: 8Gi
      cpu: 1
    limits:
      memory: 64Gi
      cpu: 2 

  storage:
    storageClass: wekafs--sdf-k8s01
    size: 1000Gi


---
apiVersion: postgresql.cnpg.io/v1
kind: Pooler
metadata:
  name: usdf-butler-pooler-rw
spec:
  cluster:
    name: usdf-butler
  instances: 3
  type: rw

  pgbouncer:
    poolMode: transaction
    parameters:
      max_client_conn: "1000"
      default_pool_size: "10"
      log_connections: "1"
      log_disconnections: "1"
      idle_transaction_timeout: "0"
      server_idle_timeout: "0"
      tcp_keepalive: "1"
      tcp_keepcnt: "1" 
      tcp_keepidle: "1" 
      tcp_keepintvl: "1"
      tcp_user_timeout: "1000"


  template:
    metadata:
      labels:
        app: pooler
    
    spec:
    
      containers:
      - name: pgbouncer
        #image: my-pgbouncer:latest
        resources:
          requests:
            cpu: "0.1"
            memory: 100Mi
          limits:
            cpu: "0.5"
            memory: 500Mi

      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - pooler
            topologyKey: "kubernetes.io/hostname"
---
