apiVersion: v1
kind: Service
metadata:
  name: usdf-butler-pooler-rw-internal
  namespace: prod
  annotations:
    metallb.universe.tf/address-pool: sdf-services
spec:
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/poolerName: usdf-butler-pooler-rw

---
apiVersion: v1
kind: Service
metadata:
  name: usdf-butler-pooler-ro-internal
  namespace: prod
  annotations:
    metallb.universe.tf/address-pool: sdf-services
spec:
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/poolerName: usdf-butler-pooler-ro
