apiVersion: v1
kind: Service
metadata:
  name: usdf-butler2-pooler-rw-internal
  namespace: prod
  annotations:
    metallb.universe.tf/address-pool: sdf-services
spec:
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/poolerName: usdf-butler2-pooler-rw

---
apiVersion: v1
kind: Service
metadata:
  name: usdf-butler2-pooler-ro-internal
  namespace: prod
  annotations:
    metallb.universe.tf/address-pool: sdf-services
spec:
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/poolerName: usdf-butler-pooler-ro

---
apiVersion: v1
kind: Service
metadata:
  name: usdf-butler2-pooler-transaction-rw
  namespace: prod2
  annotations:
    metallb.universe.tf/address-pool: sdf-services
spec:
  type: LoadBalancer
  loadBalancerIP: 172.24.5.217
  internalTrafficPolicy: Cluster
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/poolerName: usdf-butler2-pooler-transaction-rw
---
apiVersion: v1
kind: Service
metadata:
  name: usdf-butler2-pooler-rw
  namespace: database
  annotations:
    metallb.universe.tf/address-pool: sdf-dmz
spec:
  type: LoadBalancer
  loadBalancerIP: 134.79.23.203
  internalTrafficPolicy: Cluster
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/poolerName: usdf-butler2-pooler-rw
