---
apiVersion: v1
kind: Service
metadata:
  name: usdf-butler3-pooler-transaction-rw
  namespace: prod2
  annotations:
    metallb.universe.tf/address-pool: sdf-services
    metallb.universe.tf/loadBalancerIPs: 172.24.5.236
spec:
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/poolerName: usdf-butler3-pooler-transaction-rw
---
apiVersion: v1
kind: Service
metadata:
  name: usdf-butler3-pooler-session-rw
  namespace: prod2
  annotations:
    metallb.universe.tf/address-pool: sdf-services
    metallb.universe.tf/loadBalancerIPs: 172.24.5.204
spec:
  type: LoadBalancer
  internalTrafficPolicy: Cluster
  ports:
  - name: pgbouncer
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    cnpg.io/poolerName: usdf-butler3-pooler-session-rw
