resources:
- ns.yaml
# cnpg
- cnpg-butler-teststand-database.yaml
- cnpg-butler-teststand-pooler.yaml

secretGenerator:
- name: usdf-butler-teststand-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password

namespace: teststand-dev
commonLabels:
  env: teststand-dev
  app: butler-teststand
  namespace: teststand-dev
