
resources:
- ns.yaml
# cnpg
- cnpg-butler-prompt-database.yaml
- cnpg-butler-prompt-pooler.yaml
- cnpg-db-svc.yaml

secretGenerator:
- name: usdf-butler-prompt-creds
  options:
    disableNameSuffixHash: true
  files:
  - etc/.secrets/username
  - etc/.secrets/password

namespace: prompt-dev
